name: Node.js CD

on:
  workflow_call:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn

      - uses: actions/checkout@v2.3.4 

      - name: Call Deploy - CD
        if: ${{ success() }}
        id: local-action
        uses: ./.github/workflows/ci.yml
        with:
          name: "World"
      - name: Local Action Output
        run: echo "${{ steps.local-action.outputs.random }}"
