name: Node.js CI

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn
      
      - name: Running tests
        run: yarn test:ci

      - name: Running eslint
        run: yarn lint

      - name: Build project
        run: yarn build

      - name: Call Deploy - CD
        id: local-action
        uses: ./.github/workflows/cd.yml
        with:
          name: "World"
      - name: Local Action Output
        run: echo "${{ steps.local-action.outputs.random }}"


